[[language]]
name = "latex"
indent = { tab-width = 2, unit = "  " }

[language-server.texlab.config.texlab.build]
onSave = true
forwardSearchAfter = true
executable = "latexmk"
args = [
  "-verbose",
  "-file-line-error",
  "-halt-on-error",
  "-interaction=nonstopmode",
  "-synctex=1",
  "-shell-escape",
  "-pv",
  "%f"
]

[language-server.texlab.config.texlab.forwardSearch]
executable = "zathura"
args = [ "--synctex-forward", "%l:1:%f", "%p" ]
